### ISSUE TITLE
MySQL command not found in entrypoint.sh

### ISSUE THREAD

**Issue by johnaoss** [galexrt/docker-staytus#2]
Just tried installing staytus with the docker image following the commands below on Docker version 1.13.0, build 49bf474. Without any modification to the commands, I get a the following error:
`/entrypoint.sh: line 12: mysql: command not found`

Then a bunch of catastrophic ruby errors follow, and the container is never created. 

Only seems to happen when pulling from quay.io/galexrt/staytus though, not from the Docker Hub one.

**Comment by galexrt** [comment]
Can you please repull the image and try again?
For me this is fixed now.

**Comment by galexrt** [comment]
@johnaoss Is it working for you now?

**Comment by johnaoss** [comment]
Ah sorry, yes it's working now!
Thank you very much!
