### ISSUE TITLE
Create Tag with Stable Branch

### ISSUE THREAD

**Issue by ATCcodex** [galexrt/docker-staytus#3]
The reason being that the master branch does not run. Can you please create a tag from the stable branch of Staytus? Thanks!

**Comment by galexrt** [comment]
@ATCcodex Hey, I will do that. Sorry for the issue. It may take me some days as I'm currently at KubeCon though. I hope you understand.

**Comment by ATCcodex** [comment]
No problem at all! I appreciate you taking the time to do that!

**Comment by ATCcodex** [comment]
Hey @galexrt I was just checking in to see if you have made any progress on this. I know you were at the convention last week, but just wanted to check in! Thanks!

**Comment by galexrt** [comment]
@ATCcodex Hey!
I have just pushed a change to `master` to use the `stable` branch, as this image should "always" be stable and not on `master`.
The image should be build in a few minutes, see https://quay.io/repository/galexrt/staytus or https://hub.docker.com/r/galexrt/staytus/.
As a note I will move the image on Docker Hub from `docker-staytus` to `staytus` (I will leave up the old image too and keep it updated) as I don't think my PR will come through anytime soon..

Please let me know if that fixes your issue.

**Comment by ATCcodex** [comment]
`/opt/staytus/vendor/bundle/ruby/2.4.0/gems/rake-11.2.2/lib/rake/ext/fixnum.rb:4: warning: constant ::Fixnum is deprecated
/opt/staytus/vendor/bundle/ruby/2.4.0/gems/sprockets-3.6.3/lib/sprockets/digest_utils.rb:47: warning: constant ::Fixnum is deprecated
/opt/staytus/vendor/bundle/ruby/2.4.0/gems/sprockets-3.6.3/lib/sprockets/digest_utils.rb:51: warning: constant ::Bignum is deprecated
/opt/staytus/vendor/bundle/ruby/2.4.0/gems/sprockets-3.6.3/lib/sprockets/processor_utils.rb:110: warning: constant ::Fixnum is deprecated
/opt/staytus/vendor/bundle/ruby/2.4.0/gems/sprockets-3.6.3/lib/sprockets/processor_utils.rb:111: warning: constant ::Bignum is deprecated
/opt/staytus/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:206: warning: constant ::Fixnum is deprecated
/opt/staytus/vendor/bundle/ruby/2.4.0/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:155: warning: constant ::Fixnum is deprecated
/opt/staytus/vendor/bundle/ruby/2.4.0/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:155: warning: constant ::Fixnum is deprecated
/opt/staytus/vendor/bundle/ruby/2.4.0/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:155: warning: constant ::Fixnum is deprecated
/opt/staytus/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Fixnum is deprecated
/opt/staytus/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Bignum is deprecated
/opt/staytus/vendor/bundle/ruby/2.4.0/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:155: warning: constant ::Fixnum is deprecated
rake aborted!
SystemStackError: stack level too deep
/opt/staytus/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:124:in `block (2 levels) in <class:Numeric>'`

**Comment by ATCcodex** [comment]
getting a new issue any thoughts?

**Comment by galexrt** [comment]
@ATCcodex I'm working on a redone image that fixes your issue(s) and additionally uses a non-root user to run. I'll comment when it is ready (ETA about 4-12 hours).

**Comment by galexrt** [comment]
@ATCcodex I'm finished with the new image faster than expected.
I just started the container and it seems to work for me.
Could you please test if the new image works for you too?
Please note that Staytus is now running on port `8787`.

Edit: Image should be built in about 5-10 minutes.

**Comment by ATCcodex** [comment]
It looks like everything is working! Thank you for your hard work on this! Much appreciated!

**Comment by galexrt** [comment]
@ATCcodex No problem! If you experience any issues with the image, please let me know. :)
