### ISSUE TITLE
Default SMTP doesn't work properly with Amazon SES. 

### ISSUE THREAD

**Issue by dklevakin** [galexrt/docker-staytus#6]
I have tried to point default app SMTP to Amazon SES but unsuccessful.
Is it possible to sendmail instead of default email options?

**Comment by galexrt** [comment]
@dklevakin Please ask in the staytus repository, see https://github.com/adamcooke/staytus.
This is just a Docker image for staytus without MySQL server in the same image.

**Comment by galexrt** [comment]
Closing as Staytus does not seem to support this.
